import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ai-daily-video-'));
const article = path.join(root, 'article.md');
fs.mkdirSync(path.join(root, 'assets'), { recursive: true });
fs.writeFileSync(path.join(root, 'assets', '01.jpg'), 'fixture');
fs.writeFileSync(path.join(root, 'materials.json'), JSON.stringify({ items: [{ itemRank: 1, path: 'assets/01.jpg' }] }));
fs.writeFileSync(article, '# 测试日报\n\n## 01｜第一条\n\n![素材](assets/01.jpg)\n\n这是第一条新闻，包含足够的事实。\n\n## 02｜第二条\n\n这是第二条新闻，没有素材。');
const script = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'scripts', 'prepare.mjs');
const out = path.join(root, 'video', 'article');
const result = spawnSync(process.execPath, [script, article, '--out', out], { encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr);
const board = JSON.parse(fs.readFileSync(path.join(out, 'storyboard.json'), 'utf8'));
assert.equal(board.status, 'awaiting-approval');
assert.equal(board.format.width, 1080);
assert.equal(board.visualTemplate, 'ai-product-reel');
assert.equal(board.templateVersion, 1);
assert.equal(board.visualMode, 'media-first');
assert.equal(board.scenes.filter((scene) => scene.kind === 'news')[0].visual.type, 'image');
assert.equal(board.scenes.filter((scene) => scene.kind === 'news')[1].visual.type, 'card');
const output = fs.readFileSync(path.join(out, 'script.md'), 'utf8');
assert.ok(output.includes('视频口播稿'));
assert.match(output, /今天有 2 条 AI 更新，先从第一条开始。/);
assert.match(output, /这是第一条新闻，包含足够的事实。/);
assert.match(output, /这是第二条新闻，没有素材。/);
assert.doesNotMatch(output, /先看 第一条|再看 第二条/);
assert.doesNotMatch(output, /## 01|## 02|## hook|## outro/);
assert.doesNotMatch(output, /价格在变|使用门槛在变|产品入口也在变/);
assert.doesNotMatch(output, /；。/);
